---
name: DevSecOps-dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run-ansible-lint
        uses: ansible/ansible-lint@v6.22.0
        with:
          args: --profile production --exclude .github/

  auto_approve:
    runs-on: ubuntu-latest
    needs: [code-review]
    if: ${{ github.event_name == 'pull_request' && github.ref == 'main' }}
    steps:
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.15.6
